### ISSUE TITLE
Compilation error: "ifequal" method does not exist for "sInt"

### ISSUE THREAD

**Issue by adishegde** [osu-crypto/secure-kmean-clustering#1]
Hi! I get the following compilation error upon running `make`.
```
mrt20/libCluster/progCircuit.h:537:19: error: ‘class osuCrypto::sInt’ has no member named ‘ifequal’
  537 |     minBit[i]=min.ifequal(realInput[i]);
      |                   ^~~~~~~

mrt20/libCluster/progCircuit.h:537:19: error: ‘class osuCrypto::sInt’ has no member named ‘ifequal’
  537 |     minBit[i]=min.ifequal(realInput[i]);
      |                   ^~~~~~~
```
The Ivory-Runtime [submodule](https://github.com/nitrieu/Ivory-Runtime/tree/e4bb8350e6ad6fdfa5a51994fff1db86d25527a0) doesn't seem to have an implementation of `ifequal` for `sInt`. I'd appreciate any inputs on fixing this error.

**Comment by nitrieu** [comment]
fixed https://github.com/osu-crypto/secure-kmean-clustering/blob/master/Ivory-Runtime/ivory/Runtime/sInt.h#L70
thanks.
